---
title: "week1-lab"
format: html
---

# Load Libraries
```{r}
library(tidyverse)
library(janitor)
library(ggplot2)
```

# Import Data
```{r}
stressor <- read.csv("week1/data/stressor.csv")
```

# Data Exploration
```{r}
class(stressor)
dim(stressor)

# Check class of year variable
lapply(stressor_clean, class)
```


# Clean Data

```{r}
# Remove all special characters in the state and stressor columns
stressor_clean <- stressor |> 
  mutate(state = str_remove_all(state, "[^a-zA-Z ]"), 
         stressor = str_remove_all(stressor, "[^a-zA-Z ]"),
         year = as.numeric(year)) |> #Convert year variable to Numeric
  clean_names() # Convert all column names to snake_case
  
```


```{r}

# convert data from wide > long
stressor_clean <- stressor_clean |> 
  pivot_longer(cols = c("january_march", 
                        "april_june", 
                        "july_september", 
                        "october_december"),
                         names_to = "months",
                         values_to = "stress_pct") |> 
  # Convert months to quarter number-- 
  mutate(quarter = case_when(
    months == "january_march" ~ 1,
    months == "april_june" ~ 2, 
    months == "july_september" ~ 3, 
    months == "october_december" ~ 4
  )) |>
  
# Remove "United States" and "Other States" observations
  filter(state != "United States", state != "Other States") |>
  
  # Select a specific stressor
  filter(stressor == "Pesticides") |>
  
  # Select a specific state 
  filter(state == "California") |>
  
  # Calculate quarterly average for each year --
  group_by(year, quarter) |>
  summarise(avg_stress_pct = mean(stress_pct, na.rm = TRUE))
  

# print it out
print(stressor_clean)
```



```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##          some exploratory data viz + a few plot mods for practice        ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

stressor_clean |>
  ggplot(aes(x = quarter, y = avg_stress_pct, color = factor(year))) +
  geom_line(linewidth = 1) +
  geom_point(size = 3) +
  scale_color_brewer(palette = "Accent")+
  scale_x_continuous(breaks = 1:4, labels = c("Q1", "Q2", "Q3", "Q4")) +
  scale_y_continuous(labels = scales::label_number(suffix = "%")) +
  labs(
    title = "Pesticide Stress on California Bee Colonies",
    subtitle = "Quarterly averages across years",
    x = "Quarter",
    y = "Average Percent of Bee Colonies Affected",
    color = "Year"
  ) +
  theme_minimal()
```

